name: rodefortune-workflows

on:
  push:
      branches:
        - main
        - sprint-5-new
  pull_request:
      branches: 
        - main
        - sprint-5-new
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Create tool manifest
      run: dotnet new tool-manifest

    - name: Install Roslynator
      run: dotnet tool install --local roslynator.dotnet.cli

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build

    - name: Run Roslynator analysis
      run: dotnet tool run roslynator analyze RodeFortune.sln --verbosity detailed || true

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal